multiagent_techtree_1_shears_with_2_iron_ingot:
  goal: Collaborate with other agents to build a shear.
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      iron_ingot: 1
    randy:
      iron_ingot: 1
  target: shears
  number_of_target: 1
  type: techtree
  timeout : 60

multiagent_techtree_1_stone_pickaxe:
  goal: Collaborate with other agents to build an stone pickaxe
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      wooden_pickaxe: 1
    randy:
      wooden_axe: 1
  target: stone_pickaxe
  number_of_target: 1
  type: techtree
  timeout : 300

multiagent_techtree_1_iron_pickaxe_raw_iron:
  goal: Collaborate with other agents to build an iron pickaxe
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      raw_iron: 1
      stone_pickaxe: 1
    randy:
      furnace: 1
  target: iron_pickaxe
  number_of_target: 1
  type: techtree
  timeout : 300
  plan: "The agents need to smelt the raw iron to get iron ingot, then use the iron ingot to craft an iron pickaxe."

multiagent_techtree_1_iron_pickaxe_raw_iron_coal_stone:
  goal: Collaborate with other agents to build an iron pickaxe
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      raw_iron: 1
      coal: 3
      stone_pickaxe: 1
    randy:
      stone: 16
  target: iron_pickaxe
  number_of_target: 1
  type: techtree
  timeout : 300
  plan: "The agents need to 1) build the furnace 2) smelt the raw iron to get iron ingot, then 3) use the iron ingot to craft an iron pickaxe."

multiagent_techtree_1_iron_pickaxe_raw_iron:
  goal: Collaborate with other agents to build an iron pickaxe
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      raw_iron: 1
      stone_pickaxe: 1
    randy:
      furnace: 1
  target: iron_pickaxe
  number_of_target: 1
  type: techtree
  timeout : 300
  plan: "The agents need to smelt the raw iron to get iron ingot, then use the iron ingot to craft an iron pickaxe."

multiagent_techtree_wooden_pickaxe:
  goal: Collaborate with other agents to build a wooden pickaxe.
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      oak_log: 2
    randy:
      stick: 2
  target: wooden_pickaxe
  number_of_target: 1
  type: techtree
  timeout : 120

multiagent_techtree_diamond_boots:
  goal: Collaborate with other agents to build a diamond boots.
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      diamond: 2
    randy:
      diamond: 2
  target: diamond_boots
  number_of_target: 1
  type: techtree
  timeout : 120

multiagent_techtree_arrow:
  goal: Collaborate with other agents to build an arrow.
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      flint: 1
      wooden_axe: 1
    randy:
      feather: 1
  target: arrow
  number_of_target: 4
  type: techtree
  timeout : 120

multiagent_techtree_shield:
  goal: Collaborate with other agents to build a shield.
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      iron_ingot: 1
    randy:
      oak_planks: 6
  target: shield
  number_of_target: 1
  type: techtree
  timeout : 120

multiagent_build_iron_sword:
  goal: Collaborate with other agents to build an iron sword.
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      iron_ingot: 2
    randy:
      stick: 1
  target: iron_sword
  number_of_target: 1
  type: techtree
  timeout : 120

multiagent_techtree_turtle_shell:
  goal: Collaborate with other agents to build a turtle shell.
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      scute: 3
    randy:
      scute: 2
  target: turtle_shell
  number_of_target: 1
  type: techtree
  timeout : 120

multiagent_techtree_crossbow: 
  goal: Collaborate with other agents to build a crossbow.
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      iron_ingot: 1
      string: 2
    randy:
      stick: 3
      tripwire_hook: 1
  target: crossbow
  number_of_target: 1
  type: techtree
  timeout : 200

multiagent_techtree_crossbow_no_sticks:
  goal: Collaborate with other agents to build a crossbow without sticks.
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      iron_ingot: 1
      string: 2
    randy:
      tripwire_hook: 1
  target: crossbow
  number_of_target: 1
  type: techtree
  timeout : 200

multiagent_techtree_crossbow_no_iron:
  goal: Collaborate with other agents to build a crossbow without iron.
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      string: 2
      diamond_pickaxe: 1
    randy:
      stick: 3
      tripwire_hook: 1
  target: crossbow
  number_of_target: 1
  type: techtree
  timeout : 200

multiagent_techtree_shulker_box:
  goal: Collaborate with other agents to build a shulker box.
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      shulker_shell: 1
      chest: 1
    randy:
      shulker_shell: 1
  target: shulker_box
  number_of_target: 1
  type: techtree
  timeout : 200

multiagent_rescue_agent:
  goal: Get all agents to safety
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
    randy:
      oak_planks: 64
  target: rescue_agent
  number_of_target: 1
  type: rescue
  timeout : 200


